name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Run E2E tests (with JUnit reporter)
        run: |
          mkdir -p test-results
          npx cypress run --e2e --browser chrome --reporter mocha-junit-reporter --reporter-options mochaFile=test-results/junit-[hash].xml
      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
      - name: Publish JUnit to GitHub Checks
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Cypress E2E
          path: test-results/*.xml
          reporter: junit
